name: tag beta

on:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build and install
      run: |
        npm install
        npm run test
        npm run build
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git remote rm origin
        git remote add origin https://${GITHUB_ACTOR}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy:beta
