name: tag beta

on:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build and install
      run: |
        npm install
        npm run test
        npm run build
        npm run deploy:beta
