name: tag beta

on:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: master
    - name: install, test, build, deploy
      run: |
        npm install
        npm run test
        npm run build
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git checkout master
        git symbolic-ref --short HEAD
        npm run deploy:beta
