name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build and install
      run: |
        npm install
        npm run build
    - name: publish npm package
      uses: epeli/npm-release@v1
      with:
        type: stable
        token: ${{ secrets.NPM_TOKEN }}

